# Generated by Django 4.0.4 on 2022-06-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image_frontpage',
            new_name='video_profile_cover',
        ),
    ]
